on:
  push:
    branches:
      - main

name: Plan and Apply
concurrency: tf-statelock

jobs:
  plan:
    name: "Prepare Plan"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tofu
    permissions:
      contents: read
      pull-requests: write
    env:
      PGPASSWORD: ${{ secrets.PGPASSWORD }}
      BW_CLIENTID: ${{ secrets.BW_CLIENTID }}
      BW_CLIENTSECRET: ${{ secrets.BW_CLIENTSECRET }}
      BW_PASSWORD: ${{ secrets.BW_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Plan
        id: plan
        uses: ./.github/actions/common-plan
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Annotate Run
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8
        env:
          PLAN: ${{ steps.plan.outputs.plan }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // 1. Prepare format of the comment
            const output = `#### OpenTofu Initialization ‚öôÔ∏è\`${{ steps.plan.outputs.init_outcome }}\`
            #### OpenTofu Validation ü§ñ\`${{ steps.plan.outputs.validate_outcome }}\`
            <details><summary>Validation Output</summary>

            \`\`\`\n
            ${{ steps.plan.outputs.validate }}
            \`\`\`

            </details>

            #### OpenTofu Plan üìñ\`${{ steps.plan.outputs.plan_outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`tofu\`, Workflow: \`${{ github.workflow }}\`*`;

            // 2. Write to step summary
            const fs = require('fs');
            fs.appendFileSync(process.env.GITHUB_STEP_SUMMARY, output);

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          name: tfplan
          path: tofu/tfplan
  apply:
    name: "Apply Plan"
    runs-on: ubuntu-latest
    needs: plan
    environment: db-shared
    defaults:
      run:
        working-directory: tofu
    env:
        PGPASSWORD: ${{ secrets.PGPASSWORD }}
        BW_CLIENTID: ${{ secrets.BW_CLIENTID }}
        BW_CLIENTSECRET: ${{ secrets.BW_CLIENTSECRET }}
        BW_PASSWORD: ${{ secrets.BW_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Common Setup
        uses: ./.github/actions/common-setup

      - name: OpenTofu Init
        id: init
        run: tofu init

      - name: Download Plan Artifact
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7
        with:
          name: tfplan
          path: tofu

      - name: OpenTofu Apply
        id: apply
        run: tofu apply -auto-approve tfplan
